export const ELEMENT_IDS = {
  // AUTH LOGIN
  LOGIN_FORM: "loginForm",
  LOGIN_USERNAME: "loginUsername",
  LOGIN_USER_PASSWORD: "loginPassword",
  LOGIN_MESSAGE: "loginMessage",

  // AUTOMATION
  AUTOMATION_COPY_CARD_TO_MODAL: "automationcopyCardToModal",
  AUTOMATION_JOIN_CARD_TO_MODAL: "automationjoinCardToModal",
  AUTOMATION_MARK_DUEDATE_CARD_TO_MODAL: "markDueDateModal",
  AUTOMATION_MARK_DUEDATE_CARD_TO_MODAL: "setDueDateModal",
  AUTOMATION_MOVE_CARD_TO_MODAL: "moveCardToModal",
  AUTOMATION_REMOVE_FEATURE_TO_MODAL: "removeCardToModal",
  EDIT_AUTOMATION_MODAL_CONTENT: "edit-automation-modal-content",
  EDIT_AUTOMATION_MODAL: "editautomationModal",
  SELECT_LIST: "listSelect",
  OPTION: "option",
  TITLE_INPUT: "titleInput",
  DUEDATE: "duedate",
  SELECT_REMOVE_AUTOMATION: "selectRemoveAutomation",
  SELECT_BOARD: "boardSelect",
  SELECT_POSITION: "positionSelect1",

  // TODO
  MESSAGE: "message",
  PAGE_LOADING: "loading",
  DRAG_EVENT: ".dragg-from-todo",
  CARD_IMAGE: "card-img",
  OFFCANVAS: ".offcanvas",
  STYLE_BOLD: "styleBold",
  STYLE_ITALIC: "styleItalic",
  STYLE_UNDERLINE: "styleUnderline",
  ADD_LINK: "addLink",
  ADD_IMAGE: "addImage",
  MARD_CARD_FEATURE: "markCardFeature",
  WATCH_CARD_FEATURE: "watchCardFeature",
  COPY_CARD_FEATURE: "copyCardFeature",
  MOVE_CARD_FEATURE: "moveCardFeature",
  JOIN_AUTOMATION: "joinAutomation",
  MOVE_AUTOMATION: "moveAutomation",
  COPY_AUTOMATION: "copyAutomation",
  MARK_DUEDATE_AUTOMATION: "markduedateAutomation",
  SET_DUEDATE_AUTOMATION: "setduedateAutomation",
  REMOVE_CARD_FEATURE: "removeCardFeature",
  ACTIVITY_CARD_IMAGE_AREA: "activity-card-image-area",
  ATTACHMENT_CONTENT: "attachment-content",
  ACTIVITY_IMAGE_AREA: "activity-image-area",
  HISTORY_CONTENT: "history-content",
  CARD_IMAGE_PREVIEW_UPDATE: "card-image-preview-update",
  ATTACHMENT_CONTENT_HISTORY: "attachment-content-history",
  OFFCANVAS_CLOSE: "offcanvase-close",
  DELETE_TICKET: "delete-ticket",
  CARD_IMAGE_PREVIEW: "card-image-preview",
  IMAGE_PREVIEW_UPDATE: "image-preview-update",
  CARD_IMAGE_PREVIEW_IMG: "card-image-preview-img",
  TICKET_FORM: "ticketForm",
  TICKET_TITLE: "title",
  TICKET_DESCRIPTION: "description",
  TICKET_DUEDATE: "due-date",
  TICKET_ETA: "ticket_eta",
  TICKET_OWNER: "ticket-owner",
  TICKET_IMAGE: "image",
  TICKET_CARD_IMAGE: "card-image",
  TICKET_MOVE_TO: "move-to",
  KANBAN_ITEMS: ".kanban-item",
  FORM_CHECK_INPUT: ".form-check-input",
  FORM_PROGRESS_BAR: ".progress-bar",
  FORM_CHECKLIST_TITLE: "#checklist-title",
  FORM_PROGRESS_TEXT: ".col-1 span",
  FORM_COPY_CARD: "copy-card-form",
  FORM_MOVE_CARD: "move-card-form",
  FORM_MOVE_CARD_IN: "move-card-in",
  COPIED_TICKET_STATUS: "copied-ticket-status",
  SELETCT_COLOR: "selectedColor",
  ACTION_MODAL: "actionModal",
  TICKET_TAB_ACTIVITY: "tab-activity",
  TICKET_TAB_OFFCANVAS: "offcanvas-div",

  // USER LIST
  USER_ROLE: "user-role",
  USER_TABLE_BODY: "user-tbody",
  ADD_NEW_USER_FORM: "addNewUserForm",
  ADD_USER_EMAIL: "add-user-email",
  ADD_USER_PASSWORD: "add-user-password",
  ADD_USER_FIRSTNAME: "add-user-first-name",
  ADD_USER_LASTNAME: "add-user-last-name",
  FILTER_INPUT: "filterInput",
  UPDATE_USER: "update-user",
  UPDATE_USER_ROLE: "update-user-role",
  UPDATE_USER_FORM: "updateUserForm",
  UPDATE_USER_EMAIL: "update-user-email",
  UPDATE_USER_FIRSTNAME: "update-user-first-name",
  UPDATE_USER_LASTNAME: "update-user-last-name",

  // USER ROLE
  ROLE_DATA: "role-data",
  ROLE_HISTORY_DATA: "role-history-data",
  COLOR_BOXES: ".color-box",
  MENU_LINK_ACTIVE: ".menu-link-active",
  FOOTER_LINK: ".footer-link",
  O_TEXT: ".otext",
  AC_BUTTON: ".acbutton",
  BTNC_SWITCH: ".btnCSwitch",
  CARD_BG: ".card-bg",
  PROGRESS_BAR: ".progress-bar",
  PAGE_ITEM: ".page-item",
  COUNT_ROLE: "count-role",
  ROLES_CONTAINER: "rolesContainer",
  UPDATE_ROLE_FORM: "update-role-form",
  UPDATE_ROLE_NAME: "updateRoleName",

  // BACKGROUND HEADER FOOTER
  HEADER: "header",
  FOOTER: "footer",
  KANBAN_TITLE_BUTTON: "kanban-title-button",
  ADD_NEW_FORM: "add-new-form",

  // CHECKLIST
  MODAL_HEADER_TITLE: "modal-header-title",
  CHECKLIST_TITLE: "checklist-title",
  CHECKLIST_CONTAINER:"checklist-container-",
  CHECKLIST_NAME: "checklist-name",

  // COPY BOARD
  KANBAN_WRAPPER_CONTAINER: "kanban-wrapper-container",
  COPY_BOARD_NAME: "copy-board-name",

  // CREATE NEW AREA
  FROM_SHOW: "form-show",
  FROM_HIDE: "form-hide",
  ADD_BOARD_DIV: "addBoardDiv",
  KANBAN_BOARD_ADD_INPUT: "kanban-add-board-input",
  CREATE_NEW_BOARD: "create-new-board",
  COPY_BOARD_MODAL_CONTENT: "copy-board-modal-content",
  BOARD_NAME: "boardName",

  // CREATE NEW PROEJCT
  CREATE_NEW_PROJECT: "createProjectorTicket",
  PROJECT_NAME: "project-name",
  PROJECT_STATUS: "project-status",
  PROJECT_ETA: "project-eta",
  PROJECT_DESCRIPTION: "project-des",
  NAME_ERROR: "nameError",
  DESCRIPTION_ERROR: "descriptionError",
  UPDATE_PROJECT_MODAL: "update-project-modal",
  UPDATE_PROJECT_FORM: "updateProjectForm",
  UPDATE_PROJECT_NAME: "update-project-name",
  UPDATE_PROJECT_DESCRIPTION: "update-project-des",

  // DASHBOARD
  FILTER_INPUT: "filterInput",
  TABLE_BODY: "tableBody",
  SHARE_PROJECT: "shareProject",
  ACTIVE_PROJECTS_COUNTS: "active-projects-counts",
  COMPLETE_PROJECTS_COUNTS: "complete-projects-counts",
  TOTAL_PROJECTS_COUNTS: "total-projects-counts",

  // KANBAN 
  ADD_TODO_ITEM: "add-todo-item",
  IN_PROGRESS_ITEM: "add-inprogress-item",
  ADD_FOR_APPROVAL_ITEM: "add-for-approval-item",
  ADD_REJECTED_ITEM: "add-rejected-item",
  ADD_APPROVED_ITEM: "add-approved-item",
  ADD_NEW_TODO_FORM: "add-new-todo-form",
  ADD_NEW_INPROGRESS_FORM: "add-new-inprogress-form",
  ADD_NEW_FOR_APPROVAL_FORM: "add-new-for-approval-form",
  ADD_NEW_REJECTED_FORM: "add-new-rejected-form",
  ADD_NEW_APPROVED_FORM: "add-new-approved-form",
  CANCEL_FORM_1: "cancel-form-1",
  CANCEL_FORM_2: "cancel-form-2",
  CANCEL_FORM_3: "cancel-form-3",
  CANCEL_FORM_4: "cancel-form-4",
  CANCEL_FORM_5: "cancel-form-5",
  JOIN_BUTTON: "join-button",
  LEAVE_BUTTON: "leave-button",
  ADD_LABEL_FORM:"add-label-form",
};
