export const ELEMENT_IDS = {
  // AUTH LOGIN
  LOGIN_FORM: "loginForm",
  LOGIN_USERNAME: "loginUsername",
  LOGIN_USER_PASSWORD: "loginPassword",
  LOGIN_MESSAGE: "loginMessage",

  // AUTOMATION
  AUTOMATION_COPY_CARD_TO_MODAL: "automationcopyCardToModal",
  AUTOMATION_JOIN_CARD_TO_MODAL: "automationjoinCardToModal",
  AUTOMATION_MARK_DUEDATE_CARD_TO_MODAL: "markDueDateModal",
  AUTOMATION_SET_DUEDATE_CARD_TO_MODAL: "setdueDateCardToModal",
  AUTOMATION_MOVE_CARD_TO_MODAL: "moveCardToModal",
  AUTOMATION_SHARE_CARD_TO_MODAL: "shareCardToModal",
  AUTOMATION_BUTTON: "automation-buttons",
  AUTOMATION_REMOVE_FEATURE_TO_MODAL: "removeCardToModal",
  EDIT_AUTOMATION_MODAL_CONTENT: "edit-automation-modal-content",
  EDIT_AUTOMATION_MODAL: "editautomationModal",
  SELECT_LIST: "listSelect",
  OPTION: "option",
  TITLE_INPUT: "titleInput",
  DUEDATE: "duedate",
  SELECT_REMOVE_AUTOMATION: "selectRemoveAutomation",
  SELECT_BOARD: "boardSelect",
  SELECT_POSITION: "positionSelect1",
  PRINT_CARD_BTN: "printCardBtn",
  EXPORT_CARD_BTN: "exportCardBtn",
  PRINT_QR_BTN: "printQrBtn",
  QR_CONTAINER: "qrContainer",
  CODE_EMBEDD: "codeEmbedd",
  QR_MODAL: "qrModal",
  QR_BTN: "qrBtn",
  EXPORT_JSON_BTN: "exportJSONBtn",
  EXPORT_CSV_BTN: "exportCSVBtn",
  COPY_LINK_BTN: "copyLinkBtn",
  PRINT_BTN: "printBtn",
  QR_CODE_CONTAINER: "qrCodeContainer",



  // TODO
  MESSAGE: "message",
  PAGE_LOADING: "loading",
  DRAG_EVENT: ".dragg-from-todo",
  CARD_IMAGE: "card-img",
  OFFCANVAS: ".offcanvas",
  STYLE_BOLD: "styleBold",
  STYLE_ITALIC: "styleItalic",
  STYLE_UNDERLINE: "styleUnderline",
  ADD_LINK: "addLink",
  ADD_IMAGE: "addImage",
  MARD_CARD_FEATURE: "markCardFeature",
  WATCH_CARD_FEATURE: "watchCardFeature",
  COPY_CARD_FEATURE: "copyCardFeature",
  MOVE_CARD_FEATURE: "moveCardFeature",
  MOVE_ALL_CARD: "moveallcard",
  SHARE_CARD_FEATURE: "shareCardFeature",
  JOIN_AUTOMATION: "joinAutomation",
  MOVE_AUTOMATION: "moveAutomation",
  COPY_AUTOMATION: "copyAutomation",
  MARK_DUEDATE_AUTOMATION: "markduedateAutomation",
  SET_DUEDATE_AUTOMATION: "setduedateAutomation",
  REMOVE_CARD_FEATURE: "removeCardFeature",
  ACTIVITY_CARD_IMAGE_AREA: "activity-card-image-area",
  ATTACHMENT_CONTENT: "attachment-content",
  ACTIVITY_IMAGE_AREA: "activity-image-area",
  HISTORY_CONTENT: "history-content",
  CARD_IMAGE_PREVIEW_UPDATE: "card-image-preview-update",
  ATTACHMENT_CONTENT_HISTORY: "attachment-content-history",
  OFFCANVAS_CLOSE: "offcanvase-close",
  DELETE_TICKET: "delete-ticket",
  CARD_IMAGE_PREVIEW: "card-image-preview",
  IMAGE_PREVIEW_UPDATE: "image-preview-update",
  CARD_IMAGE_PREVIEW_IMG: "card-image-preview-img",
  TICKET_FORM: "ticketForm",
  TICKET_TITLE: "title",
  TICKET_DESCRIPTION: "description",
  TICKET_DUEDATE: "due-date",
  TICKET_ETA: "ticket_eta",
  TICKET_OWNER: "ticket-owner",
  TICKET_IMAGE: "image",
  TICKET_CARD_IMAGE: "card-image",
  TICKET_MOVE_TO: "move-to",
  KANBAN_ITEMS: ".kanban-item",
  FORM_CHECK_INPUT: ".form-check-input",
  FORM_PROGRESS_BAR: ".progress-bar",
  FORM_CHECKLIST_TITLE: "#checklist-title",
  FORM_PROGRESS_TEXT: ".col-1 span",
  FORM_COPY_CARD: "copy-card-form",
  FORM_MOVE_CARD: "move-card-form",
  FORM_SHARE_CARD: "share-card-form",
  FORM_MOVE_CARD_IN: "move-card-in",
  COPIED_TICKET_STATUS: "copied-ticket-status",
  SELETCT_COLOR: "selectedColor",
  ACTION_MODAL: "actionModal",
  TICKET_TAB_ACTIVITY: "tab-activity",
  TICKET_TAB_OFFCANVAS: "offcanvas-div",
  MOVE_CARD: "move-card",
  JOIN_CARD_FORM: "join-card-form",
  JOIN_USER: "joinUsers",
  JOIN_USER_MODAL: "join-user-modal",
  ELEMENT_HEADER: "element-Header",
  TAB_COMMENT: "tab-comments",
  ADD_EVENT_SIDEBAR: "add-Event-Sidebar",
  CLOSE_CARD: "closeCard",
  TICKET_TITLE_TODO: "ticket-title-todo",
  START: "start",
  TIME_SELECT: "timeSelect",
  WATCH_ICON: "watchIcon",
  WATCH_TAB_TEXT: "watchTabText",
  WATCH_TAB_BUTTON: "watchTabButton",
  USER_ACTIVITY_TAB: "user-activity-tab",
  CARD_TABLE_BODY: "card-table-body",

  // USER LIST
  USER_ROLE: "user-role",
  USER_TABLE_BODY: "user-tbody",
  ADD_NEW_USER_FORM: "addNewUserForm",
  ADD_USER_EMAIL: "add-user-email",
  ADD_USER_PASSWORD: "add-user-password",
  ADD_USER_FIRSTNAME: "add-user-first-name",
  ADD_USER_LASTNAME: "add-user-last-name",
  FILTER_INPUT: "filterInput",
  UPDATE_USER: "update-user",
  UPDATE_USER_ROLE: "update-user-role",
  UPDATE_USER_FORM: "updateUserForm",
  UPDATE_USER_EMAIL: "update-user-email",
  UPDATE_USER_FIRSTNAME: "update-user-first-name",
  UPDATE_USER_LASTNAME: "update-user-last-name",

  // USER ROLE
  ROLE_DATA: "role-data",
  ROLE_HISTORY_DATA: "role-history-data",
  COLOR_BOXES: ".color-box",
  MENU_LINK_ACTIVE: ".menu-link-active",
  FOOTER_LINK: ".footer-link",
  O_TEXT: ".otext",
  AC_BUTTON: ".acbutton",
  BTNC_SWITCH: ".btnCSwitch",
  CARD_BG: ".card-bg",
  PROGRESS_BAR: ".progress-bar",
  PAGE_ITEM: ".page-item",
  COUNT_ROLE: "count-role",
  ROLES_CONTAINER: "rolesContainer",
  UPDATE_ROLE_FORM: "update-role-form",
  UPDATE_ROLE_NAME: "updateRoleName",
  LINK_INPUT: "linkInput",
  RULE_VIEW: "rule-view",
  ADMIN_NAME: "admin-name",
  ADMIN_LOGO: "admin-logo",
  ADMIN_HASHTAG: "admin-hashtag",

  // BACKGROUND HEADER FOOTER
  HEADER: "header",
  FOOTER: "footer",
  KANBAN_TITLE_BUTTON: "kanban-title-button",
  ADD_NEW_FORM: "add-new-form",

  // CHECKLIST
  MODAL_HEADER_TITLE: "modal-header-title",
  CHECKLIST_TITLE: "checklist-title",
  CHECKLIST_CONTAINER:"checklist-container-",
  CHECKLIST_NAME: "checklist-name",

  // COPY BOARD
  KANBAN_WRAPPER_CONTAINER: "kanban-wrapper-container",
  COPY_BOARD_NAME: "copy-board-name",

  // CREATE NEW AREA
  FROM_SHOW: "form-show",
  FROM_HIDE: "form-hide",
  MOVE_FROM: "move-from",
  MOVE_TO: "move-to",
  ADD_BOARD_DIV: "addBoardDiv",
  KANBAN_BOARD_ADD_INPUT: "kanban-add-board-input",
  KANBAN_BOARD_ADD_DIV: "kanban-add-board-div",
  CREATE_NEW_BOARD: "create-new-board",
  COPY_BOARD_MODAL_CONTENT: "copy-board-modal-content",
  BOARD_NAME: "boardName",
  ENABLE_BY_DEFAULT: "enabledByDefault",
  ALL_ACTIVITY_TAB: "all-activity-tab",
  ACTIVITY_COMMENT_CONTAINER: "activity-comments-container",
  CUSTOM_FIELD_CONTENT: "custom-fields-content",
  CUSTOM_FIELD_CARD_FEATURE: "customFieldCardFeature",

  // CREATE NEW PROEJCT
  CREATE_NEW_PROJECT: "createProjectorTicket",
  PROJECT_NAME: "project-name",
  PROJECT_STATUS: "project-status",
  PROJECT_ETA: "project-eta",
  PROJECT_DESCRIPTION: "project-des",
  PROJECT_TITLE: "project-title",
  PROJECT_TITLE_INPUT: "project-title-input",
  NAME_ERROR: "nameError",
  DESCRIPTION_ERROR: "descriptionError",
  UPDATE_PROJECT_MODAL: "update-project-modal",
  UPDATE_PROJECT_FORM: "updateProjectForm",
  UPDATE_PROJECT_NAME: "update-project-name",
  UPDATE_PROJECT_DESCRIPTION: "update-project-des",
  CALENDAR: "calendar",
  CREATE_NEW_BUTTON: "createNewButton",
  CANCEL_CREATE: "cancelCreate",
  BACK_TO_EDIT: "back-to-edit",
  BACK_TO_EDIT_SETTING: "back-to-edit-settings",
  BACK_TO_EDIT_SHARE: "back-to-edit-share",
  BACK_TO_EDIT_ABOUT: "back-to-edit-about",
  BACK_TO_EDIT_AUTOMATION: "back-to-edit-automation",
  BACK_TO_EDIT_POWER_UP: "back-to-edit-power-up",
  BACK_TO_EDIT_ACTIVITY: "back-to-edit-activity",
  BACK_TO_EDIT_ARCHIVE: "back-to-edit-archive",
  BACK_TO_EDIT_CUSTOM: "back-to-edit-custom",
  BACK_TO_EDIT_LABEL: "back-to-edit-label",
  ARCHIVE_CARD_CONTAINER: "archived-cards-container",
  ARCHIVE_BOARD_CONTAINER: "archived-boards-container",

  // DASHBOARD
  FILTER_INPUT: "filterInput",
  TABLE_BODY: "tableBody",
  SHARE_PROJECT: "shareProject",
  ACTIVE_PROJECTS_COUNTS: "active-projects-counts",
  COMPLETE_PROJECTS_COUNTS: "complete-projects-counts",
  TOTAL_PROJECTS_COUNTS: "total-projects-counts",
  FILTER_ASSINGNED_TO_ME: "filter-assigned-to-me",
  FILTER_COMPLETE: "filter-complete",
  FILTER_INCOMPLETE: "filter-incomplete",
  BOARD_LINK: "boardLink",


  // KANBAN 
  ADD_TODO_ITEM: "add-todo-item",
  IN_PROGRESS_ITEM: "add-inprogress-item",
  ADD_FOR_APPROVAL_ITEM: "add-for-approval-item",
  ADD_REJECTED_ITEM: "add-rejected-item",
  ADD_APPROVED_ITEM: "add-approved-item",
  ADD_NEW_TODO_FORM: "add-new-todo-form",
  ADD_NEW_INPROGRESS_FORM: "add-new-inprogress-form",
  ADD_NEW_FOR_APPROVAL_FORM: "add-new-for-approval-form",
  ADD_NEW_REJECTED_FORM: "add-new-rejected-form",
  ADD_NEW_APPROVED_FORM: "add-new-approved-form",
  CANCEL_FORM_1: "cancel-form-1",
  CANCEL_FORM_2: "cancel-form-2",
  CANCEL_FORM_3: "cancel-form-3",
  CANCEL_FORM_4: "cancel-form-4",
  CANCEL_FORM_5: "cancel-form-5",
  JOIN_BUTTON: "join-button",
  ELEMENT_BUTTON: "element-Button",
  ELEMENT_ID: "element-Id",
  LEAVE_BUTTON: "leave-button",
  ADD_LABEL_FORM:"add-label-form",
  SAVE_LABEL_BUTTON:"saveLabelButton",
  OPEN_ACTION_BUTTON:"openActionButton",
  LABEL_TEXT:"labelText",
  SAVE_CUSTOM_BUTTON:"saveCustomButton",
  BUTTON_TITLE:"buttonTitle",
  PROJECT_NAME:"projectName",
  PROJECT_LEADER:"projectLeader",
  PROJECT_STATUS:"projectStatus",
  CHANGE_WORKSPACE_BTN:"changeWorkspaceBtn",
  WORKSPACE_DROPDOWN:"workspaceDropdown",
  SELECTED_WORKSPACE_DISPLAY:"selectedWorkspaceDisplay",
  SAVE_COMMENT_PERMISSION_BTN:"saveCommentPermissionBtn",
  COMMENT_PERMISSION_DISPLAY:"commentPermissionDisplay",
  SAVE_VOTING_PERMISSION_BTN:"saveVotingPermissionBtn",
  VOTING_PERMISSION_DISPLAY:"votingPermissionDisplay",
  SAVE_ADD_PERMISSION_BTN:"saveAddPermissionBtn",
  ADD_REMOVE_PERMISSION_DISPLAY:"addRemovePermissionDisplay",
  WORKSPACE_EDITING_ADMINS:"workspaceEditingAdmins",
  CARD_COVER_CHECKBOX:"cardCoversCheckbox",
  COMPLETE_CARD_CHECKBOX:"completeCardCheckbox",
  REMOVE_VOTE:"removeVote",

  // MODAL
  CHECKLIST_MODAL: "checklistModal",
  CUSTOM_FIELD_MODAL: "customFieldModal",
  CUSTOM_FIELDS_FROM: "customFieldsForm",

  // LOCAL STORAGE
    LOGGED_USERID: "logged-user-id",
    LOGGED_USERNAME: "logged-username",
    LOGGED_FIRSTNAME: "logged-first-name",
    LOGGED_USERROLE_ID: "logged-user-role-id",
    LOGGED_USERROLE_NAME: "logged-user-role-name",
    LOGGED_ACTIVITY: "lastActivity",
    LOGGED_ROLE_ID: "logged-role-id",
    LOGGED_ROLE_NAME: "logged-role-name",
    LOGGED_SESSION_EXPIRE: "sessionExpireTime",
    LOGGED_SESSION_LS: "sessionIs",
    LOG_CONTAINER: "logContainer",
    LOG_OUT_BUTTON: "logoutButton",

    // mirror modal
    MIRROR_BOARD_SELECT: "boardSelect",
    MIRROR_LIST_SELECT: "listSelect",
    MIRROR_BTN: "mirrorBtn",
    TAB_CUSTOM_CONTAINER: "tabCustomFieldsContainer",
    POSITION_INPUT: "positionInput",
    MIRROR_CARD_FEATURE: "mirrorCardFeature",
    MIRROR_MODAL: "mirrorModal",
};
